CREATE TABLE platform (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  base_url VARCHAR(500) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_platform_name UNIQUE (name)
);

CREATE TABLE course (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  platform_id BIGINT NOT NULL REFERENCES platform(id),
  external_id_hash CHAR(64) NOT NULL,
  title VARCHAR(500) NOT NULL,
  url VARCHAR(1000) NOT NULL,
  provider VARCHAR(200) NULL,
  area VARCHAR(80) NULL,
  free_flag BOOLEAN NOT NULL DEFAULT TRUE,
  start_date DATE NULL,
  end_date DATE NULL,
  status_text VARCHAR(200) NULL,
  price_text VARCHAR(200) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_course_external UNIQUE (external_id_hash)
);

CREATE TABLE course_snapshot (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL REFERENCES course(id),
  collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status_text VARCHAR(200) NULL,
  price_text VARCHAR(200) NULL,
  raw_json TEXT NULL
);

CREATE TABLE run_log (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  platform_id BIGINT NOT NULL REFERENCES platform(id),
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMPTZ NULL,
  success_flag BOOLEAN NOT NULL DEFAULT FALSE,
  pages_scanned INT NOT NULL DEFAULT 0,
  items_found INT NOT NULL DEFAULT 0,
  items_new INT NOT NULL DEFAULT 0,
  items_updated INT NOT NULL DEFAULT 0,
  error_summary TEXT NULL
);

CREATE INDEX ix_course_platform_updated ON course(platform_id, updated_at DESC);
CREATE INDEX ix_course_area_updated     ON course(area,       updated_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_platform_updated_at
BEFORE UPDATE ON platform
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_course_updated_at
BEFORE UPDATE ON course
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
